import add_strings
import array_find_kth_element
import array_find_largest_element
import array_sort_unsorted_array
import dictionary_anagram
import array_common_elements
import array_largest_sum
import array_maximum_subarray
import array_most_frequently_occurring
import array_pair_sum
import array_rotation
import dynamic_programming_best_time_to_buy_and_sell_stock
import dictionary_first_unique_character_in_string
import linked_list_merge_two_sorted_lists
import string_longest_common_prefix
import string_longest_substring
import string_reverse_words
import string_unique_character_in_string
import string_valid_palindrome
import stack_valid_parentheses
import array_find_largest_element
__name__ == '__main__'

nums = [3, 2, 1, 5, 6, 4]
k = 2
print(array_find_kth_element.find_kth_smallest(nums, k))
